name: Renew Let's Encrypt certificate (Wildcard)

on:
  workflow_dispatch:



jobs:
  renew-letsencrypt-certificate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      DNS_ZONE_RESOURCE_ID: ${{ vars.DNS_ZONE_RESOURCE_ID }}
      KEY_VAULT_RESOURCE_ID: ${{ vars.KEY_VAULT_RESOURCE_ID }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      KEY_VAULT_CERT_NAME: ${{ vars.KEY_VAULT_CERT_NAME }}
      PRODUCTION: ${{ vars.PRODUCTION }}
      LETS_ENCRYPT_EMAIL: ${{ secrets.LETS_ENCRYPT_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_LETS_ENCRYPT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Prepare infrastructure, role assignments and prerequisites
        run: |
          az deployment sub create --verbose --location italynorth --template-file letsencrypt/main.bicep \
            --parameters mainDnsZoneResourceId=$DNS_ZONE_RESOURCE_ID \
            mainCertKeyVaultResourceId=$KEY_VAULT_RESOURCE_ID \
            domain=$DOMAIN_NAME

      - name: Setup azuredns.ini
        run: |
          az deployment sub show --name main --query properties.outputs.azurednsini.value -o tsv > azuredns.ini
        working-directory: letsencrypt

      - name: Build and Push customer Docker image
        run: |
          docker build . -t $(az deployment sub show --name main --query properties.outputs.registryServername.value -o tsv)/h2floh/azurecertbot:latest
          az acr login -n $(az deployment sub show --name main --query properties.outputs.registryServername.value -o tsv)
          docker push $(az deployment sub show --name main --query properties.outputs.registryServername.value -o tsv)/h2floh/azurecertbot:latest
        working-directory: letsencrypt

      - name: Run Container Instance to renew certificate and store
        run: |
          az deployment sub create --verbose --location italynorth --template-file letsencrypt/aci.bicep \
            --parameters mainCertKeyVaultResourceId=$KEY_VAULT_RESOURCE_ID \
            email=$LETS_ENCRYPT_EMAIL \
            domain=$DOMAIN_NAME \
            certname=$KEY_VAULT_CERT_NAME \
            production=$PRODUCTION \
            registryServername=$(az deployment sub show --name main --query properties.outputs.registryServername.value -o tsv) \
            userAssignedIdentityPrincipalId=$(az deployment sub show --name main --query properties.outputs.umsiPrincipalId.value -o tsv) \
            userAssignedIdentityResourceId=$(az deployment sub show --name main --query properties.outputs.umsiResourceId.value -o tsv)


  cleanup-environment:
    needs: renew-letsencrypt-certificate
    if: ${{ always() }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_LETS_ENCRYPT_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      # - name: Cleanup environment
      #   run: |
      #     az group delete --name rg-temporary --yes