name: Access private resources with Azure Network connected Runners

on:
  workflow_dispatch:
    inputs:
      keyvault-name: 
        description: 'The name of the Azure Key Vault'
        required: true

jobs:
  set-and-read-secret:
    runs-on: 
      group: vnet-runners
      labels: linux
    steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set secret in Azure Key Vault
        run: |
          az keyvault secret set --vault-name ${{ inputs.keyvault-name }}  --name "MySecret" --value "MySecretValue"

      - name: Read secret from Azure Key Vault
        run: |
          secret=$(az keyvault secret show --vault-name ${{ inputs.keyvault-name }} --name "MySecret" --query value -o tsv)
          echo "The secret value is: $secret"